// Run: node tests/auth-api.cjs. Exercises the actual handler with a mocked upstream.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const Module = require('node:module');
const ts = require('typescript');
const { NextRequest } = require('next/server');
const filename = require('node:path').resolve('app/api/auth/[action]/route.ts');
const compiled = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const handler = new Module(filename, module);
handler.filename = filename;
handler.paths = module.paths;
handler._compile(compiled, filename);
const { POST } = handler.exports;
let calls = [];
let result = { error: false, token: 'test-session', guestId: 'guest-42' };
let status = 200;
global.fetch = async (url, options) => { calls.push({ url, options, body: JSON.parse(options.body) }); return Response.json(result, { status }); };
const request = (action, data, headers = {}) => POST(new NextRequest(`http://localhost:3000/api/auth/${action}`, { method: 'POST', headers: { origin: 'http://localhost:3000', 'content-type': 'application/json', ...headers }, body: JSON.stringify(data) }), { params: Promise.resolve({ action }) });
(async () => {
  let response = await request('login', { email: ' user@example.com ', password: 'password', remember: true });
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { error: false });
  assert.deepEqual(calls.at(-1).body, { handle: 'user@example.com', password: 'password' });
  assert.match(response.headers.get('set-cookie'), /coinzy_session=test-session/);
  assert.match(response.headers.get('set-cookie'), /HttpOnly/);
  assert.match(response.headers.get('set-cookie'), /SameSite=lax/i);
  assert.match(response.headers.get('set-cookie'), /Max-Age=/);
  response = await request('signup', { email: 'user@example.com', password: 'password', name: ' Collector ', timezone: 'Asia/Kolkata', language: 'en' }, { cookie: 'coinzy_guest_id=guest-42' });
  assert.equal(response.status, 200);
  assert.deepEqual(calls.at(-1).body, { email: 'user@example.com', fullName: 'Collector', password: 'password', confirmPass: 'password', timezone: 'Asia/Kolkata', language: 'en', guestId: 'guest-42' });
  assert.doesNotMatch(response.headers.get('set-cookie'), /Max-Age=/);
  response = await request('guest', {}, { cookie: 'coinzy_guest_id=guest-42' });
  assert.equal(response.status, 200);
  assert.deepEqual(calls.at(-1).body, { guestId: 'guest-42' });
  assert.match(response.headers.get('set-cookie'), /coinzy_guest_id=guest-42/);
  result = { error: false };
  response = await request('forgot', { email: 'user@example.com' });
  assert.equal(response.status, 200);
  assert.deepEqual(calls.at(-1).body, { handle: 'user@example.com' });
  response = await request('reset', { email: 'user@example.com', password: 'newpassword', code: '123456' });
  assert.equal(response.status, 200);
  assert.deepEqual(calls.at(-1).body, { email: 'user@example.com', password: 'newpassword', token: '123456' });
  assert.equal(response.headers.get('set-cookie'), null);
  result = { error: true, reason: 'Incorrect password' };
  response = await request('login', { email: 'user@example.com', password: 'password' });
  assert.equal(response.status, 400);
  assert.equal((await response.json()).reason, 'Incorrect password');
  assert.equal(response.headers.get('set-cookie'), null);
  result = { error: false };
  assert.equal((await request('login', { email: 'user@example.com', password: 'password' })).status, 502);
  const count = calls.length;
  assert.equal((await request('google', {})).status, 404);
  assert.equal((await request('login', { email: 'bad', password: 'password' })).status, 400);
  assert.equal((await request('reset', { email: 'user@example.com', password: 'password', code: 'bad' })).status, 400);
  assert.equal((await request('guest', {}, { origin: 'https://other.example' })).status, 403);
  assert.equal(calls.length, count);
  result = { error: true, reason: 'Service unavailable' }; status = 503;
  assert.equal((await request('guest', {})).status, 502);
  global.fetch = async () => { throw new Error('Network unavailable'); };
  assert.equal((await request('guest', {})).status, 502);
  console.log('PASS: five auth contracts, cookies, guest reuse, validation, origin checks and upstream errors');
})().catch(error => { console.error(error); process.exitCode = 1; });
